SIM ?= icarus
FST ?= -fst
TOPLEVEL_LANG ?= verilog

SRC_DIR = $(PWD)/../src
PROJECT_SOURCES ?= tt_um_globaltimer_sched.v

ifneq ($(GATES),yes)
SIM_BUILD = sim_build/rtl
VERILOG_SOURCES += $(SRC_DIR)/$(PROJECT_SOURCES)
else
SIM_BUILD = sim_build/gl
COMPILE_ARGS    += -DGL_TEST -DFUNCTIONAL -DUSE_POWER_PINS -DSIM -DUNIT_DELAY=\#1
VERILOG_SOURCES += $(PDK_ROOT)/sky130A/libs.ref/sky130_fd_sc_hd/verilog/primitives.v
VERILOG_SOURCES += $(PDK_ROOT)/sky130A/libs.ref/sky130_fd_sc_hd/verilog/sky130_fd_sc_hd.v
VERILOG_SOURCES += $(PWD)/gate_level_netlist.v
endif

COMPILE_ARGS += -I$(SRC_DIR)

TOPLEVEL ?= tt_um_globaltimer_sched
COCOTB_TOPLEVEL ?= $(TOPLEVEL)

IVERILOG_ARGS += -g2012 -s $(TOPLEVEL)
COCOTB_TEST_MODULES = test

include $(shell cocotb-config --makefiles)/Makefile.sim
